version: '3.1'

services:
  stats-server:
    build: statistics/
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/explore-with-me
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: liza1990

  stats-db:
    image: postgres:15.3-alpine3.18
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=explore-with-me
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=liza1990

  ewm-service:
    build: main-service/
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      MAIN_SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/main-service
      MAIN_SPRING_DATASOURCE_USERNAME: postgres
      MAIN_SPRING_DATASOURCE_PASSWORD: liza1990

  ewm-db:
    image: postgres:15.3-alpine3.18
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=main-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=liza1990