version: '3.1'

services:
  stats-server:
    build: statistics/
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: liza1990

  stats-db:
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=liza1990

  ewm-service:
    build: main-service
    ports:
      - "8080:8080"
    depends_on:
      - main-service-db
    environment:
      MAIN_SPRING_DATASOURCE_URL: jdbc:postgresql://main-service-db:5432/main-service-db
      MAIN_SPRING_DATASOURCE_USERNAME: postgres
      MAIN_SPRING_DATASOURCE_PASSWORD: liza1990
      STATS_SERVER_URL: http://stats-server:9090

  main-service-db:
    image: postgres:14-alpine
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=main-service-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=liza1990