DROP TABLE IF EXISTS hits CASCADE;
CREATE TABLE IF NOT EXISTS hits (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app varchar(250) NOT NULL,
    uri varchar(250) NOT NULL,
    ip varchar(45) NOT NULL,
    timestamp timestamp WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_hits PRIMARY KEY (
        id
     )
);